# Dependabot configuration for Adversarial Comparator
# Automatically updates dependencies and security patches

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Rome"
    reviewers:
      - "ninomirabile"
    assignees:
      - "ninomirabile"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    ignore:
      # Ignore specific packages that might cause issues
      - dependency-name: "torch"
        versions: ["2.0.0", "2.0.1"]
      - dependency-name: "torchvision"
        versions: ["0.15.0", "0.15.1"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Europe/Rome"
    reviewers:
      - "ninomirabile"
    assignees:
      - "ninomirabile"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5

  # Docker dependencies (if applicable)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "Europe/Rome"
    reviewers:
      - "ninomirabile"
    assignees:
      - "ninomirabile"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    open-pull-requests-limit: 3 