name: Pull Request Check

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  pr-check:
    name: PR Quality Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black isort pytest
    
    - name: Check code formatting
      run: |
        echo "🔍 Checking code formatting..."
        black --check --diff src/ || echo "⚠️ Code formatting issues found. Run 'black src/' to fix."
        isort --check-only --diff src/ || echo "⚠️ Import sorting issues found. Run 'isort src/' to fix."
    
    - name: Run linting
      run: |
        echo "🔍 Running linting checks..."
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run basic tests
      run: |
        echo "🧪 Running basic tests..."
        python -m pytest tests/ -v --tb=short
    
    - name: Check documentation
      run: |
        echo "📚 Checking documentation..."
        required_files=("README.md" "QUICKSTART.md" "DISCLAIMER.md")
        for file in "${required_files[@]}"; do
          if [ -f "$file" ]; then
            echo "✅ $file exists"
          else
            echo "❌ $file missing"
            exit 1
          fi
        done
    
    - name: Check for sensitive data
      run: |
        echo "🔒 Checking for sensitive data..."
        if grep -r "password\|secret\|key\|token" src/ --exclude="*.pyc" --exclude="__pycache__" | grep -v "#" | grep -v "example"; then
          echo "⚠️ Potential sensitive data found in code"
          exit 1
        else
          echo "✅ No obvious sensitive data found"
        fi 